spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://streat-user:8080
          predicates:
            - Path=/api/users/**
        - id: store
          uri: http://streat-store:8080
          predicates:
            - Path=/api/stores/**
    config:
      uri: http://localhost:8888
      label: main
  config:
    import: "configserver:"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    use-root-path: true
    urls:
      - name: Store API
        url: https://j11a307.p.ssafy.io/api/stores/v3/api-docs
      - name: user API
        url: https://j11a307.p.ssafy.io/api/users/v3/api-docs
