spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8882
          predicates:
            - Path=/api/users/**
        - id: store
          uri: http://localhost:8081
          predicates:
            - Path=/api/stores/**


server:
  port: 8787