spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8882
          predicates:
            - Path=/api/users/**

server:
  port: 8787