spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://localhost:8882
          predicates:
            - Path=/api/users/**
        - id: store
          uri: http://localhost:8081
          predicates:
            - Path=/api/stores/**
        - id: order
          uri: http://localhost:8883
          predicates:
            - Path=/api/orders/**
        - id: product
          uri: http://localhost:8083
          predicates:
            - Path=/api/products/**
server:
  port: 8787

springdoc:
  swagger-ui:
    urls:
      - name: Store API
        url: http://localhost:8787/api/stores/v3/api-docs
      - name: user API
        url: http://localhost:8787/api/users/v3/api-docs
      - name: Order API
        url: http://localhost:8787/api/orders/v3/api-docs
      - name: Product API
        url: http://localhost:8787/api/products/v3/api-docs