spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://streat-user:8080
          predicates:
            - Path=/api/users/**
        - id: store
          uri: http://streat-store:8080
          predicates:
            - Path=/api/stores/**
        - id: order
          uri: http://streat-order:8080
          predicates:
            - Path=/api/orders/**
        - id: product
          uri: http://streat-product:8080
          predicates:
            - Path=/api/products/**
        - id: payment
          uri: http://streat-payment:8080
          predicates:
            - Path=/api/payments/**
    config:
      uri: http://localhost:8888
      label: main
  config:
    import: "configserver:"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    use-root-path: true
    urls:
      - name: Store API
        url: http://j11a307.p.ssafy.io/api/stores/v3/api-docs
      - name: user API
        url: http://j11a307.p.ssafy.io/api/users/v3/api-docs
      - name: Order API
        url: http://j11a307.p.ssafy.io/api/orders/v3/api-docs
      - name: Product API
        url: http://j11a307.p.ssafy.io/api/products/v3/api-docs
      - name: Payment API
        url: http://j11a307.p.ssafy.io/api/payments/v3/api-docs