spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://streat-user:8080
          predicates:
            - Path=/api/users/**
<<<<<<< Updated upstream
=======
        - id: store
          uri: http://streat-store:8080
          predicates:
            - Path=/api/stores/**
        - id: order
          uri: http://streat-order:8080
          predicates:
            - Path=/api/orders/**
>>>>>>> Stashed changes
    config:
      uri: http://localhost:8888
      label: main
  config:
    import: "configserver:"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    use-root-path: true
    urls:
      - name: Store API
<<<<<<< Updated upstream
        url: http://localhost:8787/api/stores/v3/api-docs
=======
        url: http://localhost:8080/api/stores/v3/api-docs
      - name: user API
        url: http://localhost:8080/api/users/v3/api-docs
      - name: Order API
        url: http://localhost:8080/api/orders/v3/api-docs
>>>>>>> Stashed changes
