spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: user
          uri: http://streat-user:8080
          predicates:
            - Path=/api/users/**
    config:
      uri: http://localhost:8888
      label: main
  config:
    import: "configserver:"
