spring:
  datasource:
    url: jdbc:mysql://j11a307.p.ssafy.io:3306/streat?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Seoul
  # cloud:
  #   gateway:
  #     globalcors:
  #       cors-configurations:
  #         '[/**]':
  #           allowed-origins:
  #             - http://70.12.247.148:8787
  #             - http://localhost:8787
  #           allowed-methods:
  #             - GET
  #             - POST
  #             - PUT
  #             - DELETE
  #             - PATCH
  #             - OPTIONS
  #           allowed-headers:
  #             - '*'
  #           allow-credentials: true
  data:
    redis:
      host: streat-redis
      port: 6379
kakao:
  redirect-uri: https://j11a307.p.ssafy.io/services/users/login/kakao/auth
  app-key: 2348144c073d82c2759f313c40d3c9c9
  token:
    url: https://kauth.kakao.com/oauth/token
  user-info:
    url: https://kapi.kakao.com/v2/user/me

jwt:
  salt: STREAT-SALT-VALUE-40932999-071e-4368-a21f-6aa4b5fa16b0
  access-token:
    expiretime: 360000000000

streat:
  internal-request: streat-internal-request
  redis:
    logout-prefix: "logout-time:"

filter:
  include-paths:
    - /api/users/
  exclude-paths:
    - /api/users/login/
    - /api/users/swagger-ui/
    - /api/users/v3/api-docs
    - /api/users/createToken
    - /api/users/profile

firebase:
  api-url: https://fcm.googleapis.com/v1/projects/streat-c2387/messages:send
  config-path: fcm-config.json

cloud:
  aws:
    credentials:
      accessKey: AKIAWOAVST3DJGLEX47H
      secretKey: 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
    s3:
      bucketName: streat-bucket
    region:
      static: ap-northeast-2
    stack:
      auto: false

toss:
  secret-key: dGVzdF9za19PUnpkTWFxTjN3NURlYVpFbXZueXI1QWtZWFFHOg==
  payments:
    confirm-url: https://api.tosspayments.com/v1/payments/confirm
    base-url: https://api.tosspayments.com/v1/payments