spring:
  application:
    name: config
  cloud:
    config:
      server:
        encrypt:
          key: skdljfhefwklxx23423@streat
        git:
          uri: https://lab.ssafy.com/s11-fintech-finance-sub1/S11P21A307.git
          username: thswnsqja
          password: MzuTG3V9qxUpZhxzi-Vf
          search-paths: "/backend"
