spring:
  application:
    name: user

eureka:
  client:
    service-url:
      defaultZone: http://streat-eureka:8080/eureka/ # 해당 경로가 아니라도 설정이 반드시 필요함. 실행하지 않으면 docker-compose의 환경이 주입이 안됨.

server:
  servlet:
    context-path: /api/users