spring:
  application:
    name: user
  cloud:
    config:
      uri: http://streat-config:8080
      label: backend
  config:
    import: "configserver:"

eureka:
  client:
    service-url:
      defaultZone: http://streat-eureka:8080/eureka/ # 해당 경로가 아니라도 설정이 반드시 필요함. 실행하지 않으면 docker-compose의 환경이 주입이 안됨.

server:
  servlet:
    context-path: /api/users

kakao:
  redirect-uri: http://localhost:8787/api/users/login/kakao/redirect
  app-key: 2348144c073d82c2759f313c40d3c9c9